### ISSUE TITLE
Plugins still not working

### ISSUE THREAD

**Issue by superblack4** [Kxnrl/AdvMusicPlayer#10]
Hello @Kxnrl ,

Thx you so much for ur plugin and develop it a lot. However, I have install everything you said, search for a song, and then there is NO bot appear to play music even there is a description telling me that a BOT has join my server to play music

Also, there is no option to customize volume and to hear the song by myself.

Can you fix this problem? I love this plugin so much and I hope to see it go to work properly xD

Thx you and have a nice day!

**Comment by Kxnrl** [comment]
Did you host server with param -nobots?
self player not support in csgo branch now. maybe add in the feature

**Comment by superblack4** [comment]
> Did you host server with param -nobots?
> self player not support in csgo branch now. maybe add in the feature

I did not put -nobots in my server param
Also, I can't stop the music unless i use ADMIN command

Do i need to put bot_quota to other value than 0?

**Comment by superblack4** [comment]
> Did you host server with param -nobots?
> self player not support in csgo branch now. maybe add in the feature

![Untitled](https://user-images.githubusercontent.com/38873974/91595368-a10f0c80-e98d-11ea-960b-7b945dcfe955.png)
this is my server parameter

**Comment by Kxnrl** [comment]
is csgo server?

**Comment by superblack4** [comment]
> is csgo server?

yes it is csgo server

**Comment by Kxnrl** [comment]
check sourcemod/data/music/  has cache files?

**Comment by superblack4** [comment]
> check sourcemod/data/music/ has cache files?

![image](https://user-images.githubusercontent.com/38873974/91595647-15e24680-e98e-11ea-9caf-e4a5c1c5469d.png)

**Comment by superblack4** [comment]
> check sourcemod/data/music/ has cache files?

what should i do?

**Comment by Kxnrl** [comment]
so the player menu was shown, but u can not hear anything?

**Comment by superblack4** [comment]
> so the player menu was shown, but u can not hear anything?

Exactly like u said, show the menu but cannot hear anything

**Comment by Kxnrl** [comment]
okay. my bad, i forgot package ffmpeg. xD. you need to download ffmpeg.exe to addons\sourcemod\data\audio_ext\

**Comment by superblack4** [comment]
> okay. my bad, i forgot package ffmpeg. xD. you need to download ffmpeg.exe to addons\sourcemod\data\audio_ext\

Can you please give me the link to download it? I appreciate a lot for ur help brother xD

**Comment by Kxnrl** [comment]
ffmpeg.org

**Comment by superblack4** [comment]
> ffmpeg.org
Thx you so much for ur help, you should include in the next update. Also, please add self player, volume customize option as soon as possible. I love ur plugin a lot brother xD

**Comment by Kxnrl** [comment]
btw, audio-ext with youtubedl support,

**Comment by superblack4** [comment]
> ffmpeg.org

btw, do i need to create a folder call audio_ext in data folder? Because i cannot see one

**Comment by Kxnrl** [comment]
yes

**Comment by superblack4** [comment]
> yes

OMG it is working now. Thank you so much for ur support xD

**Comment by Kxnrl** [comment]
btw, some songs is not playable by copyright limits.

**Comment by superblack4** [comment]
> btw, some songs is not playable by copyright limits.

I got it. I hope u can add those options to this plugin xD
