### ISSUE TITLE
compile ext on linux

### ISSUE THREAD

**Issue by Yhycat** [Kxnrl/AdvMusicPlayer#13]
I need this extension compiled for Linux, but I'm not familiar in the world of C++ and Sourcemod extensions unfortunately. 
can you help compile it into .so file. 

thanks

**Comment by Kxnrl** [comment]
https://github.com/Kxnrl/AdvMusicPlayer/commit/79d1f3aeb10c4397c1b301e3b9de8d3a77f2b424
