### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by Round1337** [Kxnrl/AdvMusicPlayer#16]
Hello, i faced with problem, when i install  audio.ext.so i received this mistake: <FAILED> file "audio.ext.so": cannot load vaudio library: libuuid.so.1: cannot open shared object file: No such file or directory
Can you help me? (in OC i installed libuuid.so.1 last version)
OC Debian

**Comment by Kxnrl** [comment]
audio.ext issue should post to here https://github.com/PerfectLaugh/SM-Ext-Audio

**Comment by Round1337** [comment]
Well thank you
