### ISSUE TITLE
It stoped working

### ISSUE THREAD

**Issue by penalte** [Kxnrl/AdvMusicPlayer#18]
it does not work since update.

 [advmusicplayer.smx] SteamWorks -> API_DownloadSound_SteamWorks -> HTTP Response failed: 404
 [advmusicplayer.smx] SteamWorks -> API_PrepareSong -> HTTP Response failed: 404

**Comment by strikerlulu** [comment]
Sed :(
Is the engine down @Kxnrl ?

**Comment by strikerlulu** [comment]
Server out of free space ? 
```
Notice: Undefined index: length in /var/www/music/api/v4/library/kmusic.php on line 114

Warning: file_put_contents(): Only 0 of 1438125 bytes written, possibly out of free disk space in /var/www/music/api/v4/library/kmusic.php on line 185
```

**Comment by Kxnrl** [comment]
> Server out of free space ?
> 
> ```
> Notice: Undefined index: length in /var/www/music/api/v4/library/kmusic.php on line 114
> 
> Warning: file_put_contents(): Only 0 of 1438125 bytes written, possibly out of free disk space in /var/www/music/api/v4/library/kmusic.php on line 185
> ```

Fixed
