### ISSUE TITLE
Audio extension

### ISSUE THREAD

**Issue by superblack4** [Kxnrl/AdvMusicPlayer#8]
advmusicplayer.smx (Advanced Music Player): Required extension "Audio" file("audio.ext") not running

I have download System2 extension but still i got this error
I even download Steamwork extension too but still got this error

Where can i download this audio extension Kxnrl?

**Comment by superblack4** [comment]
@Kxnrl  any solutions to fix this bro?

**Comment by Kxnrl** [comment]
https://github.com/PerfectLaugh/sm-ext-Audio

**Comment by superblack4** [comment]
> https://github.com/PerfectLaugh/sm-ext-Audio

![image](https://user-images.githubusercontent.com/38873974/89732607-1025cf00-da7a-11ea-852c-77205448e65f.png)

**Comment by ppppd** [comment]
Same problem, that repo does not exist. Can you help, @Kxnrl ?

**Comment by penalte** [comment]
+1

**Comment by Kxnrl** [comment]
I will contact the author

**Comment by penalte** [comment]
@Kxnrl thank you but i know nothing about compiling extensions, can you help?

**Comment by Kxnrl** [comment]
> @Kxnrl thank you but i know nothing about compiling extensions, can you help?

I added prebuild binary. 
https://github.com/Kxnrl/AdvMusicPlayer/commit/f861a99a8dd4b4e3c7bb2c33d5548530338712d7
